### ISSUE TITLE
To Stop Crashing On Unsupported Nodes

### ISSUE THREAD

**Issue by Jim-Kroovy** [SpectralVectors/TransMat#1]
Just a small change you could make (i don't have time to make a pull request or test this today) but something like processing only supported nodes should stop crashing on unsupported nodes 👍 

`nodes = [n for n in material.node_tree.nodes if n.type in supported_nodes]`

I also suggest having a look at a function like this one below and iterating on bl_rna.properties, you should be able to dynamically get all the node properties much easier without all the ifs conditions. 

When i find the time i'll be coming back here and helping you code this for sure 😄 

```python
def Get_Node_RNA_Properties(node):
    dictionary = {}
    for prop in node.bl_rna.properties:
        if not prop.is_readonly:
            # might need to process some of the values before writing to python so you don't get errors...
            dictionary[prop.identifier] = getattr(node, prop.identifier)
    return dictionary

**Comment by SpectralVectors** [comment]
Implemented your code, thanks, works a treat!
Yeah, when I see a million conditionals, I know that there are better ways to do it.
RNA properties came up a few times when I was searching solutions for bugs early on, I'll have to look into them a little more.
Thanks!
